### PR TITLE
Ensure we pick a compressed transfer syntax when available

### PR DESCRIPTION
**Pull request by robedwardsagfa**
(cherry picked from commit ac9d587658412f06d1214a1cabda7408b76c79ca)

### CODE REVIEW

**Comment by robedwardsagfa** [comment]
One other thing I should point out is this change replicates what was done previously in dcm4che2.  Allowing a prioritized ordering seemed to have been inadvertently removed with the migration to dcm4che3.

**Comment by gunterze** [comment]
Rejected, because an application which reads the configuration from a LDAP backend according [PS3.15 H.1. Application Configuration Management Profile](http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_H.1) may get the list of Transfer Syntaxes of a particular Transfer Capability in different order for each read, and therefore would behave nondeterministic.

**Comment by hczedik** [comment]
Hi Gunter,
if the order of the list of Transfer Syntaxes returned by LDAP is nondeterministic, couldn't we simply sort them (e.g. alphabetically) then so that a predictable sorting is ensured?

**Comment by gunterze** [comment]
But selecting always the literal first Transfer Syntax is less sensitive than the current behavior to select the first in the offered list in the Presentation Context.

**Comment by hczedik** [comment]
Yes, but then it is better configurable for those using a configuration backend that supports setting a fixed order of transfer capabilities.
Is LDAP really always unsorted? Seems like a disadvantage.

**Comment by gunterze** [comment]
Behavior should not depend on the configuration backend!

You may e.g. define an additional attribute on Device, AE and/or Transfer Capability level "Preferred Transfer Syntax" with a list of Transfer Syntax UIDs stored in LDAP  in a single value using any delimiter character...

**Comment by gunterze** [comment]
Fixed by #218 15ccd97

**Pull request closed without merging**
