### PR TITLE
dcm4che-tool-jpg2dcm: Failed to extract Image Pixel Attributes from JPEG header

### PR DESCRIPTION
**Pull request by vrindanayak**
dcm4che/dcm4chee-arc-light#757

### CODE REVIEW

**Comment by vrindanayak** [comment]
Locally `mvn clean install` works on the branch `dcm4chee-arc-light#757`

**Comment by vrindanayak** [comment]
Hi Hermann, 
The build works locally on the branch dcm4chee-arc-light#757. Is there an issue on Travis side?

**Comment by hczedik** [comment]
Hi Vrinda,
the Travis build is fine: https://travis-ci.org/dcm4che/dcm4che/builds/240709119

We are currently in the process of reviewing this change. It looks fine, but will probably need to do some changes in our server code, as it is using the class MediaTypes, where you renamed and changed some constants. Sorry for the delay.

**Comment by vrindanayak** [comment]
Hi Hermann,
No problem, I was just wondering if I had to do something from my side to fix this. The only reason for me commenting on this pull request today was that once this pull request is merged, I would also like to request changes for dcm4che/dcm4chee-arc-light#756. Thank you.

**Pull request merged**
