### PR TITLE
fix: transcode between JPEGLosslessSV1 and JPEGLSLossless

### PR DESCRIPTION
**Pull request by adrianog3**
When data from source BufferedImage was byte array the code fails when performed cast.

The proposed solution is to check if the data from source BufferedImage is already in bytes, and copy it directly.

### CODE REVIEW

**Review by jhonatasfender — APPROVED** [review]

**Comment by adrianog3** [comment]
The related issue is: https://github.com/dcm4che/dcm4che/issues/1323

**Review by lucianomukudai — APPROVED** [review]

**Review by romilson-junio — APPROVED** [review]

**Comment by nroduit** [comment]
If you're interested in using Java APIs directly for transcoding, then take a look at this [library](https://github.com/nroduit/weasis-dicom-tools), which is based on dcm4che3 but where image management has been completely redesigned and no longer uses imageio (except to register the new native code).

The above-mentioned problem is not present when using the transcoding API.

Here are some new features or behaviors:

-  Less complex code for reading, writing and tanscoding images (remove Java reflection in stream classes)
-  Only one pixel model (interleaved mode) returned by the image reader. Sub-sampled models are automatically convert to normal interleaved image. This eliminates the complexity at the end of the chain.
-  Keep pixel data as a native object when reading, writing, converting, resizing, and all the image processing operations (except for the last operation of display, needs to convert into Bufferedimage)
-  Return raw pixel data (byte, short, ushort, int, float, double) without applying modality, voi and presentation LUT
-  Large API for image processing and conversion
-  ImageDescriptor contains the modality and voi LUT, and the overlay data.
-  ImageReaderDescriptor has two sub-classes: 1) DicomFileInputStream: handle DICOM file 2) BytesWithImageDescriptor: handle image content in bytes
-  ImageReader contains getLazyPlanarImages which allows to apply several processing functions without having pixel in memory (image is read only when calling PlanarImage.get()). This is particularly interesting for handling multiframe separately and not loading all frames in memory.

**Comment by adrianog3** [comment]
Hi @nroduit, thank you for the answer.

I use the transcoding feature on many parts of the system, so migrating to [weasis-dicom-tools](https://github.com/nroduit/weasis-dicom-tools) would take a long time as it requires doing regression testing.

Given the context, I'd like to know if my PR might be the solution to the problem until I migrate to weasis-dicom-tools, or if in fact I should migrate now.

**Comment by nroduit** [comment]
Yes, that seems to fix the issue for this particular case. I don't have permission to merge.

**Comment by adrianog3** [comment]
I don't know if I should be asking this question here, but i'm trying to evaluate the use of the [weasis-dicom-tools](https://github.com/nroduit/weasis-dicom-tools) library and i'm having trouble importing the latest version: **5.29.2.2**.

Adding the dependency:

`<dependency>
    <groupId>org.weasis</groupId>
    <artifactId>weasis-dicom-tools</artifactId>
    <version>5.19.1</version>
</dependency>`

And this repository:

`<repository>
    <id>mvn-repo-master</id>
    <url>https://raw.github.com/nroduit/mvn-repo/master/</url>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
</repository>`

Only version **5.19.1** is available.

Is there another repository I should add to get access to version **5.29.2.2**?

image

**Comment by adrianog3** [comment]
Thank you very much @nroduit, 

I analyzed the [weasis-dicom-tools](https://github.com/nroduit/weasis-dicom-tools) code and concluded that the Transcoder does not allow to provide InputStream and OutputStream.

These parameters is very important for my use case, because I do the reading dcm files in a certain transfer syntax, and I send it through the http protocol using another transfer syntax, so generating files is unnecessary.

Can I implement this improvement and open a pull request?

**Comment by adrianog3** [comment]
Thank you very much @nroduit, 

I analyzed the [weasis-dicom-tools](https://github.com/nroduit/weasis-dicom-tools) code and concluded that the Transcoder does not allow to provide **OutputStream**.

This parameter is very important for my use case, because I do the reading dcm files in a certain transfer syntax, and I send it through the http protocol using another transfer syntax, so generating files is unnecessary.

Is it possible to implement this improvement? If you allow me I can carry out this implementation.

**Comment by adrianog3** [comment]
Can anyone review and merge this PR?

**Pull request merged**
